Add test-report to deploy workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,7 +9,6 @@ jobs:
     runs-on: ubuntu-latest
     permissions:
       contents: write
-      checks: write
     outputs:
       self_mutation_happened: ${{ steps.self_mutation.outputs.self_mutation_happened }}
     env:
@@ -34,13 +33,6 @@ jobs:
         with:
           name: test-reports
           path: cdk.out/
-      - name: Add Test Report to Pull Request
-        if: success() || failure()
-        uses: dorny/test-reporter@v1
-        with:
-          name: Jest Unit Tests
-          path: test-reports/junit.xml
-          reporter: jest-junit
       - name: Find mutations
         id: self_mutation
         run: |-
@@ -52,12 +44,12 @@ jobs:
         with:
           name: .repo.patch
           path: .repo.patch
-      # - name: Fail build on mutation
-      #   if: steps.self_mutation.outputs.self_mutation_happened
-      #   run: |-
-      #     echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
-      #     cat .repo.patch
-      #     exit 1
+      - name: Fail build on mutation
+        if: steps.self_mutation.outputs.self_mutation_happened
+        run: |-
+          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
+          cat .repo.patch
+          exit 1
   self-mutation:
     needs: build
     runs-on: ubuntu-latest
