Try this

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -52,12 +52,12 @@ jobs:
         with:
           name: .repo.patch
           path: .repo.patch
-      - name: Fail build on mutation
-        if: steps.self_mutation.outputs.self_mutation_happened
-        run: |-
-          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
-          cat .repo.patch
-          exit 1
+      # - name: Fail build on mutation
+      #   if: steps.self_mutation.outputs.self_mutation_happened
+      #   run: |-
+      #     echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
+      #     cat .repo.patch
+      #     exit 1
   self-mutation:
     needs: build
     runs-on: ubuntu-latest
